import { Web3Exception } from '@injectivelabs/exceptions';
/**
 * Preparing and broadcasting
 * Ethereum transactions
 */
export class Web3Broadcaster {
    walletStrategy;
    ethereumChainId;
    constructor({ walletStrategy, ethereumChainId, }) {
        this.walletStrategy = walletStrategy;
        this.ethereumChainId = ethereumChainId;
    }
    async sendTransaction(args) {
        const { walletStrategy, ethereumChainId } = this;
        try {
            const chainId = args.ethereumChainId || ethereumChainId;
            const txHash = await walletStrategy.sendEvmTransaction(args.tx, {
                address: args.address,
                ethereumChainId: chainId,
            });
            await walletStrategy.getEvmTransactionReceipt(txHash, chainId);
            return txHash;
        }
        catch (e) {
            throw new Web3Exception(new Error(e.message));
        }
    }
}
